# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isAdmin', models.BinaryField()),
                ('fbID', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('UserToken', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('timeStamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
