# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='UserToken',
            new_name='userToken',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='player',
            name='levelTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
