# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20161228_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isAdmin',
        ),
    ]
