# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fbID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
