# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20170108_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='userToken',
        ),
    ]
