# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='ans_text',
            new_name='ans',
        ),
    ]
