# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20161223_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
