# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20170115_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=question.models.upload_location),
        ),
    ]
