# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20170115_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, upload_to=question.models.upload_location),
        ),
        migrations.AlterField(
            model_name='question',
            name='script',
            field=models.FileField(blank=True, upload_to=question.models.upload_location),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, upload_to=question.models.upload_location),
        ),
    ]
